import { RowndSchema } from "./types";

export const PLUGIN_ID = "supertokens-plugin-rownd";

export const PLUGIN_SDK_VERSION = ["23.0.0", "23.0.1", ">=23.0.1"];
export const HANDLE_BASE_PATH = "/plugin/rownd";
export const PUBLIC_TENANT_ID = "public";

export const DEFAULT_ROWND_SCHEMA: RowndSchema = {
  email: {
    display_name: "Email",
    type: "string",
    data_category: "pii_basic",
    owned_by: "user",
    required: false,
    unique: false,
    user_visible: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
  zip_code: {
    display_name: "Zip code",
    type: "string",
    data_category: "pii_basic",
    owned_by: "user",
    required: false,
    unique: false,
    user_visible: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
  google_id: {
    display_name: "Google ID",
    type: "string",
    data_category: "custom",
    owned_by: "app",
    required: false,
    unique: false,
    user_visible: false,
    read_only: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
  last_name: {
    display_name: "Last name",
    type: "string",
    data_category: "pii_basic",
    owned_by: "user",
    required: false,
    unique: false,
    user_visible: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
  nick_name: {
    display_name: "Nick name",
    type: "string",
    data_category: "pii_basic",
    owned_by: "user",
    required: false,
    unique: false,
    user_visible: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
  first_name: {
    display_name: "First name",
    type: "string",
    data_category: "pii_basic",
    owned_by: "user",
    required: false,
    unique: false,
    user_visible: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
  phone_number: {
    display_name: "Phone number",
    type: "string",
    data_category: "pii_basic",
    owned_by: "user",
    required: false,
    unique: false,
    user_visible: true,
    revoke_after: "",
    required_retention: "",
    collection_justification: "",
    opt_out_warning: "",
  },
};
