name: Release Packages

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to checkout and publish from"
        required: true
        default: "main"
        type: string
      skip_tests:
        description: "Skip running tests before publishing"
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    needs: prepare
    if: ${{ !github.event.inputs.skip_tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test

  release:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Release new packages
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
